language: php

php:
  - 7.0
  - 7.1

sudo: true

cache: vendor

before_install:
  - sudo apt-get update  -yqq
  - sudo apt-get install -yqq libssh2-1-dev libssh2-php openssh-client openssh-server proftpd
  # ls -l $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
  # extensionspath=`ls -l $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/|grep no-debug-zts|awk '{print $9}'|tr -d '\n'`
  # echo $extensionspath
  # cp tests/bin/ssh2.so $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/$extensionspath/
  # echo "extension=ssh2.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - sh tests/before_script.sh
  - composer install --no-progress --no-ansi --no-interaction --profile

script:
  # php -r "phpinfo();"
  # cat $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - rm -rf /tmp/guzzle-cacert.pem
  - composer test

notifications:
  email: false

# vim:fdl=0:sts=2:sw=2:ts=2
