language: php

php:
  - 7.0

sudo: true

cache: vendor

before_install:
  - sudo apt-get update  -yqq
  - sudo apt-get install -yqq libssh2-1-dev libssh2-php openssh-client openssh-server proftpd
  # ls -l $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/
  # extensionspath=`ls -l $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/|grep no-debug-zts|awk '{print $9}'|tr -d '\n'`
  # echo $extensionspath
  # cp tests/bin/ssh2.so $HOME/.phpenv/versions/$(phpenv version-name)/lib/php/extensions/$extensionspath/
  # echo "extension=ssh2.so" >> $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini

before_script:
  - sh tests/before_script.sh
  - composer install --no-progress --no-ansi --no-interaction --profile

script:
  # php -r "phpinfo();"
  # cat $HOME/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer test

after_success:
  - mkdir -p /tmp/build/coverage /tmp/build/document
  - composer quality
  - composer coverage
  - composer document
  - if [ $TRAVIS_PHP_VERSION = '7.0' ] && [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ]; then sh tests/generate-api.sh; fi

notifications:
  email: false

env:
  global:
    secure: HS4cdnBuyeGhKyDDFSfhDIHctaWLVRrjyMvTK/XzCM8DsNVZ/w6TxebOi7zsnAqYn57LUtt8ytPM0XuGVtJfmFLlWaEBLN3TtdRq2ZYmb0A8KqYaXp/PvxEQiDtzh/7AA/3y13VVhqNKhJMg6+WJtgpO9Ht8XW0AUhdhuZj6jT7Jkx9GpW6iVHGB7Y0eRbwRvlr5es6uOaFmy9SgYuk4N9odyIbCIfoua6D1jBevN/B5CEx2I6MImLheyNJRKJ+JBwYwThg2Tcmuxrp+wfM1mpHKcykgdd7XWq8fx8eJthkfgrVL07HbeiQB87RtwWa1H7WPKrmayeM8+CbD1EIUoHWUbijsV0QUCSH1follvZh0F9ub0MmJK7lKkLXCtfImhjGyf0Y3cJT294eVq1mUF7G68zeVRvguyDuXb3ykOv9D4Bm5nSRFeZcxo5FZTKVmz5ny8V4I/SC6GkHcdjaA9lvyP8s+7eFjRxVOJeZXM3uQzPcVBYewJZ+ck2ERIJ3dUw3S8tzwtsr8dDwrGT1xhnjpBqDLTZPOT8ba1CwnHI6K7hblH2N90YDRhyYFw3QV8knYRhQdDOvZzJa1cPuo5C8QOiGwzOmT2CR6HJ+GZRqRcePJ587p1h82cvCWRpjCIVOHlHtkM5IxyaSvwKDX+3Fs6JMMZLvPkR0+6uUalC4=

# vim:fdl=0:sts=2:sw=2:ts=2
